name: Headless Chrome UI test for /users/id/tasks

on:
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    name: Headless chrome UI test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
          
      - name: nodeJS and npm version
        run: npm -v
        
      - name: npm init
        run: npm init -y
        
      - name: capute screenshot in headless chrome and save it
        run: google-chrome --headless --disable-gpu --screenshot=capture-users-id-tasks.png https://nscstrdevusw2tuecommon.z5.web.core.windows.net/users/41/tasks
