name: Deploy UI

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Build website
      run: |
        cd ui
        npm install
        npm run build
        
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
      with:
        source-path: ui/build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}