name: Deploy Azure functions from NSC branch

on:
  push:
    branches:
      - development

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions'  
  PYTHON_VERSION: '3.8'         

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout Repository GitHub Action'
      uses: actions/checkout@main 

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment # this is the script that sets up python
      uses: actions/setup-python@v1 
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip' # installs all the packages necessary to run the functions
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: Azure Functions Action
      uses: Azure/functions-action@v1.3.1
      id: fa
      with:
        app-name: 'nsc-functionsapp-team1'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
