name: Deploy Azure functions from NSC branch

on:
  push:
    branches:
      - development

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions'  
  PYTHON_VERSION: '3.8'         

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout Repository GitHub Action'
      uses: actions/checkout@main 

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment # this is the script that sets up python
      uses: actions/setup-python@v1 
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip' # installs all the packages necessary to run the functions
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Azure Functions Action'
      uses: Azure/functions-action@v1.3.1
      id: fa
      with:
        app-name: 'nsc-functionsapp-team1'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: '<publishData><publishProfile profileName="nsc-functionsapp-team1 - Web Deploy" publishMethod="MSDeploy" publishUrl="nsc-functionsapp-team1.scm.azurewebsites.net:443" msdeploySite="nsc-functionsapp-team1" userName="$nsc-functionsapp-team1" userPWD="lH0qirFgBpcvTHm1YAPeZkjwDFhM58A0mWlFPixd8skBpcoZpRWZhg39nGLa" destinationAppUrl="http://nsc-functionsapp-team1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="nsc-functionsapp-team1 - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-mwh-007.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="nsc-functionsapp-team1\$nsc-functionsapp-team1" userPWD="lH0qirFgBpcvTHm1YAPeZkjwDFhM58A0mWlFPixd8skBpcoZpRWZhg39nGLa" destinationAppUrl="http://nsc-functionsapp-team1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="nsc-functionsapp-team1 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="nsc-functionsapp-team1.scm.azurewebsites.net:443" userName="$nsc-functionsapp-team1" userPWD="lH0qirFgBpcvTHm1YAPeZkjwDFhM58A0mWlFPixd8skBpcoZpRWZhg39nGLa" destinationAppUrl="http://nsc-functionsapp-team1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="nsc-functionsapp-team1 - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-mwh-007dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="nsc-functionsapp-team1\$nsc-functionsapp-team1" userPWD="lH0qirFgBpcvTHm1YAPeZkjwDFhM58A0mWlFPixd8skBpcoZpRWZhg39nGLa" destinationAppUrl="http://nsc-functionsapp-team1.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
