name: Performance-Test

on:  
  push:
    branches:
      - derek-task4-sprint3

jobs:
  slsart-perf:
    name: slsart Performance Test
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      STAGE_NAME: merge-perf-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install serverless and serverless-artillery
        run: |
          npm install -g serverless@1.38.0 serverless-artillery
      # once a folder with slsart script.yml and serverless.yml are created and in the repo
      # we can copy them into the working dir to run those specific tests with those configurations
      # - currently this just runs the defaults
      # examples for future:
      #- run: cp ./slsart/script.yml ./
      # - run: cp ./slsart/serverless.yml ./
      
      - name: Deploy, invoke, remove functions
        run: |
          ~/.npm-global/bin/slsart deploy --stage $STAGE_NAME 
          ~/.npm-global/bin/slsart invoke -s ../../testing/Serverless-Artillery/serverless-artillery-test-users-id-api.yml --stage $STAGE_NAME > ../../testing/results/users_id_api_script.json
          ~/.npm-global/bin/slsart remove --stage $STAGE_NAME 

        #Azure Login 

      - name: Azure Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
            
        #Upload File
      - name: uploading to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.19.1
          inlineScript: |
            az storage blob upload  --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }}  --container-name ${{ secrets.BLOB_CONTAINER }}   --name artilleryReport_${{ steps.date.outputs.date }}.json --file  artilleryReport_${{ steps.date.outputs.date }}.json
        
        # Azure logout
      - name: logout
        run: |
          az logout